---
- id: squonk2-job-image-tag-checker
  name: Squonk2 job image tag checker
  description: This hook checks image tags in job and nextflow definitions
  entry: /entrypoint.sh
  language: docker
  pass_filenames: false
  require_serial: true
